### ISSUE TITLE
first supporter gone rogue :)

### ISSUE THREAD

**Issue by vitaly-t** [codenautas/pg-promise-strict#1]
Greetings!

I thought you liked [pg-promise](https://github.com/vitaly-t/pg-promise) library when you posted there. 

What prompted you to write your own version? Was it in any way not usable for your projects?

I wonder, because I'm always looking to make improvements. ;)

Regards,

**Comment by emilioplatzer** [comment]
Greetings!

I like pg-promise for two reasons:
- Promises
- explicit control of how many rows you expect. In July 2014 I write a made my own of concept [motor-db](https://github.com/emilioplatzer/motor-db) of this and feels good. 

But I need a module with 100% test coverage. This is the main reason for write my own version. 

Then I think that a good pg-with-promise could have:
- the same functions with same name and same parámeters, only changing the last callback with a Promise
- a way of explicit control of how may rows
- no rewrites: calling original pg modue every time I can. 
- reflect client.query with optional callback (if you pass a callback all rows are fetched), with pg-promise-strict you can chose to execute the query and fetch all or to fecth [row by row](https://github.com/codenautas/pg-promise-strict#example-with-fetch-row-by-row):

``` js
    client.query("SELECT name FROM users").onRow(function(row){
        console.log(row.name);
    }).then(function(result){
        console.log('ready.',result.rowCount,'rows processed');
        client.done();
    });
```

`onRow` recives a callback to call row by row and returns a Promise that resolves when the las row was fetched and rejects when error.

**Comment by vitaly-t** [comment]
I'll get back to it later today, but for now...
_no rewrites: calling original pg modue every time I can._
pg-promise does that already, by the way, with method [queryRaw](https://github.com/vitaly-t/pg-promise/wiki/Learn-by-Example#affected-rows) ;)

I could always throw 100% coverage into it, but my first attempt at it wasn't successful, so maybe you can help me with that ;)

**Comment by vitaly-t** [comment]
> But I need a module with 100% test coverage. This is the main reason for write my own version.

[pg-promise](https://github.com/vitaly-t/pg-promise) now has 100% coverage :)

**Comment by vitaly-t** [comment]
Closing, since there was no response :)
